apiVersion: v1
kind: Secret
metadata:
  name: airflow-db-credentials
  namespace: airflow
type: Opaque
data:
  # These values will be injected by CI/CD pipeline
  # DO NOT commit actual credentials to repository
  username: ""
  password: ""
