executor: "CeleryExecutor"

images:
  airflow:
    repository: mintah/airflow-custom
    tag: latest

extraEnv: |-
  - name: CONFIG_PATH
    value: /opt/airflow/dags/repo/configs/config.yaml
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: aws-credentials
        key: AWS_ACCESS_KEY_ID
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: aws-credentials
        key: AWS_SECRET_ACCESS_KEY
  - name: AWS_DEFAULT_REGION
    valueFrom:
      secretKeyRef:
        name: aws-credentials
        key: AWS_DEFAULT_REGION
  - name: MLFLOW_TRACKING_URI
    valueFrom:
      secretKeyRef:
        name: mlflow-config
        key: MLFLOW_TRACKING_URI
  - name: INFERENCE_API_URL
    valueFrom:
      secretKeyRef:
        name: mlflow-config
        key: INFERENCE_API_URL
  - name: AIRFLOW__METRICS__STATSD_ON
    value: "True"
  - name: AIRFLOW__METRICS__STATSD_HOST
    value: statsd-exporter.monitoring.svc.cluster.local
  - name: AIRFLOW__METRICS__STATSD_PORT
    value: "9125"
  - name: AIRFLOW__METRICS__STATSD_PREFIX
    value: airflow


dags:
  persistence:
    enabled: false
    size: 1Gi
    storageClassName: longhorn
  gitSync:
    enabled: true
    repo: https://github.com/Lay-ke/MLOps-Project.git
    branch: main
    rev: HEAD
    depth: 1
    subPath: pipelines

logs:
  persistence:
    enabled: true
    size: 1Gi
    storageClassName: longhorn

postgresql:
  enabled: true
  auth:
    username: airflow
    password: airflow
    database: airflow
  primary:
    persistence:
      enabled: true
      size: 8Gi
      storageClass: longhorn

redis:
  enabled: true
  persistence:
    enabled: true
    size: 1Gi

data:
  metadataConnection:
    user: airflow
    pass: airflow
    protocol: postgresql
    host: airflow-postgresql
    port: 5432
    db: airflow
    sslmode: disable

flower:
  enabled: false

web:
  defaultUser:
    enabled: true
    username: admin
    password: admin

service:
  type: NodePort
  nodePort: 30080